services:
  # 1. Base de datos local aislada
  mongo_local:
    image: mongo:8
    container_name: caseta_mongo_local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Tu Backend en Node.js
  api-server:
    build:
      context: .
      dockerfile: docker/scripts/backend.Dockerfile
    container_name: caseta-backend
    env_file:
      - ./backend/.env
    ports:
      - "3004:3004"
    depends_on:
      - mongo_local
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads

  # 3. Tu Frontend en React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: caseta-frontend
    ports:
      - "5177:5177"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data: